# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d66629bf671e278ba9e8196a15097316a96b539e3ffcca682cc5fc25fab2a5d781c6ded19b3567a4ca6e5bb3439a7ef3e68c42e94871ac2be7abc8a65a494f

test:
  secret_key_base: 831c2c00285569b61eef62dea056824a44f2bedc6a6ac08ac9523c1fffb659ec81bb2554fd002ec00d1a79bfe3813dee689339645e9b1a8b826f0d044fc11fd6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
